/*
 * CallPanel.java
 *
 * Created on 2005年12月28日, 下午 12:54
 */

package marsping.component;

import marsping.component.button.DirectionButton;
import marsping.component.type.Direction;
import marsping.component.type.Floor;

/**
 *
 * @author  MarsPing
 */
public class CallPanel extends javax.swing.JPanel {
    
    private DirectionButton upButton,downButton;
    private StatusPanel sp;
    private Floor floor;
    private Door door;
    
    /** Creates new form CallPanel */
    public CallPanel(Floor floor,ElevatorController controller) {
        this.floor = floor;
        sp = new StatusPanel();
        door = new Door();
        add(door);
        
        initComponents();
        panel.add(sp, 0);
        upButton = new DirectionButton(Direction.UP, floor, controller);
        downButton = new DirectionButton(Direction.DOWN, floor, controller);
        
        buttonPanel.add(upButton);
        buttonPanel.add(downButton);
    }
    
    public void setBorder(){
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2), floor.toString(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("新細明體", 1, 14), new java.awt.Color(255, 255, 255)));
    }
    
    public void resetBorder(){
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), floor.toString(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("新細明體", 1, 14), new java.awt.Color(255, 255, 255)));
    }
    
    public void openDoor(){
        door.openDoor();
    }
    
    public void closeDoor(){
        door.closeDoor();
    }
    
    public void setStatus(){
        sp.setStatus();
    }
    
    public void resetButton(Direction dir){
        switch(dir){
            case UP:
                upButton.resetButton();
                break;
            case DOWN:
                downButton.resetButton();
                break;
        }
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), floor.toString(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("新細明體", 1, 14), new java.awt.Color(255, 255, 255)));
        setPreferredSize(new java.awt.Dimension(70, 150));
        panel.setBackground(new java.awt.Color(102, 102, 102));
        panel.setPreferredSize(new java.awt.Dimension(70, 120));
        buttonPanel.setLayout(new java.awt.GridLayout(2, 1, 3, 5));

        buttonPanel.setBackground(new java.awt.Color(102, 102, 102));
        panel.add(buttonPanel);

        add(panel);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
    
}
