/*
 * StatusPanel.java
 *
 * Created on 2005年12月28日, 上午 11:24
 * Download:http://www.codefans.net
 */

package marsping.component;

import marsping.component.type.Direction;
import marsping.component.type.Floor;

/**
 *
 * @author  MarsPing
 */
public class StatusPanel extends javax.swing.JPanel {
    
    /** Creates new form StatusPanel */
    public StatusPanel() {
        initComponents();
    }
    
    public void setStatus() {
        Floor cf = Elevator.getCurrentFloor();
        Floor tf = ElevatorController.getTargetFloor();
        
        floorLabel.setText(cf.toString());
        upLabel.setForeground(new java.awt.Color(153, 153, 153));
        downLabel.setForeground(new java.awt.Color(153, 153, 153));
        
        if(tf==null)
            return;
        
        if(cf.ordinal()<tf.ordinal()){
            upLabel.setForeground(new java.awt.Color(254, 180, 82));
        } else if(cf.ordinal()>tf.ordinal()){
            downLabel.setForeground(new java.awt.Color(254, 180, 82));
        } else if(Direction.getDirection().ordinal()==Direction.UP.ordinal()){
            upLabel.setForeground(new java.awt.Color(254, 180, 82));
        } else if(Direction.getDirection().ordinal()==Direction.DOWN.ordinal()){
            downLabel.setForeground(new java.awt.Color(254, 180, 82));
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        upLabel = new javax.swing.JLabel();
        floorLabel = new javax.swing.JLabel();
        downLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        upLabel.setBackground(new java.awt.Color(51, 51, 51));
        upLabel.setFont(new java.awt.Font("Dialog", 1, 18));
        upLabel.setForeground(new java.awt.Color(153, 153, 153));
        upLabel.setText(Direction.UP.toString());
        add(upLabel);

        floorLabel.setBackground(new java.awt.Color(51, 51, 51));
        floorLabel.setFont(new java.awt.Font("Dialog", 1, 18));
        floorLabel.setForeground(new java.awt.Color(254, 180, 82));
        floorLabel.setText(Elevator.getCurrentFloor().toString());
        add(floorLabel);

        downLabel.setBackground(new java.awt.Color(51, 51, 51));
        downLabel.setFont(new java.awt.Font("Dialog", 1, 18));
        downLabel.setForeground(new java.awt.Color(153, 153, 153));
        downLabel.setText(Direction.DOWN.toString());
        add(downLabel);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel downLabel;
    private javax.swing.JLabel floorLabel;
    private javax.swing.JLabel upLabel;
    // End of variables declaration//GEN-END:variables
    
}
