package com.huiton.cerp.login;
import java.util.*;
/**
 * Title:        CERP测试框架
 * Description: 资源文件
 * Copyright:    Copyright (c) 2000
 * Company:      BRITC
 * @author zaj
 * @version 1.0
 */

public class LoginRes extends java.util.ListResourceBundle{
    static final Object[][] contents = new String[][]{
        { "ABOUT", "关于" },
        { "PRINT","打印"},
        { "TONGUE","英文"},
        { "EXIT","退出"},
        { "WANT_EXIT","您真的要退出吗?"},
        { "HELP","帮助"},
        { "COMPANY","公司"},
        { "COPYRIGHT","版权所有"},
        { "VERSION","版本"},
        { "WELCOME","欢迎"},
        { "LOGIN","登录"},
        { "COMPANY_NAME","公司名称"},
        { "USER_CODE","用户代码"},
        { "USER_NAME","用户名称"},
        { "USER_UNIQUE_NO","用户唯一号"},
        { "USER_IP","用户IP"},
        { "LOGIN_TIME","登录时间"},
        { "OFFLINE","断线"},
        { "PASSWORD","密码"},
        { "PASSWD","修改密码"},
        { "YEAR","年份"},
        { "LENGTH_SHOULD_BETWEEN","长度应该界于"},
        { "AND","和"},
        { "SCOPE","之间"},
        { "YEAR_SHOULD_BE_4_DIGITS","年份须为有效的四位数字"},
        { "RELOGIN","重新登录"},
        { "SET","设置"},
        { "SUCCEED","成功"},
        { "FAILED","失败"},
        {"COPYRIGHT_INF","2001-2020"},
        {"VERSION_INF","CERP e-ERP"},
        {"NO_USER","该用户不存在"},
        {"WRONG_PASSWORD","密码错误"},
        {"DB_ERROR","数据库连接较忙，请稍候再试"},
        {"UNKNOWN_ERROR","内部服务器出错"},
        {"NO_YEAR","该年份不存在"},
        {"IP_FORBID","该帐号禁止此IP访问"},
        {"STATUS_FORBID","该用户已被禁止访问"},
        {"USER_OVERFLOW","该帐号在线人数已满，请稍候再试"},
        {"COMPANY_USER_OVERFLOW","此公司在线人数已满，请稍候再试"},
        {"OLD_PASSWORD","原密码"},
        {"NEW_PASSWORD","新密码"},
        {"REVIEW_NEW_PASSWORD","确认新密码"},
        {"SUBMIT","确认"},
        {"RESET","重置"},
        {"PASSWD_SUCCEED","密码成功修改！"},
        {"PASSWD_FAILED","修改密码失败！"},
        {"PASSWD_NOT_MATCH","原密码不对！"},
        {"PASSWD_DB_ERROR","用户不存在！"},
        {"PASSWD_IS_FORBID","密码禁止修改！"},
        {"MUST_EQUAL","必须等于"},
        {"MY_FAVOR","我的收藏夹"},
        {"WANT_DEL","确认删除吗？"},
        {"WANT_DEL_ALL","您真的要删除所有满足条件的记录吗？"},
        {"QUERY_STYLE","查询方式"},
        {"CONDITION","条件"},
        {"SELECT_PAGE","当页全选"},
        {"SELECT_ALL","全选"},
        {"DELETE","删除"},
        {"MODIFY","修改"},
        {"UPDATE","修改确认"},
        {"VIEW","浏览"},
        {"NEW","增加"},
        {"OPERATION","操作"},
        {"QUERY","查询"},
        {"OPERATION","操作"},
        {"FAVOR_TYPE","收藏类型"},
        {"FAVOR_NAME","收藏名称"},
        {"PROG_NAME","程序名称"},
        {"SEQ_NO","序号"},
        {"BACK","返回"},
        {"PARAMS_WRONG","参数错"},
        {"CLOSE","关闭"},
        {"DUPLICATE_KEY","键值重复"},
        {"RECORD_EXISTS","该页面已收藏过!"},
        {"PLEASE","请"},
        {"CHOOSE","选择"},
        {"START_STOP_TIME","起止时间"},
        {"EVENT_TYPE","事件类型"},
        {"LOCATION","地点"},
        {"SUBJECT","主题"},
        {"MORE","更多..."},
        {"DAILY","按日"},
        {"WEEKLY","按周"},
        {"MONTHLY","按月"},
        {"DATE","日期"},
        {"START_TIME","开始时间"},
        {"STOP_TIME","终止时间"},
        {"SUBJECT","主题"},
        {"LOCATION","地点"},
        {"EVENT_TYPE","事件类型"},
        {"PRIV_FLAG","私事"},
        {"DEAL_FLAG","完成"},
        {"EVENT_DESC","事件描述"},
        {"DEAL_DESC","处理描述"},
        {"SAVE_BACK","保存返回"},
        {"SAVE_CONTINUE","保存继续"},
        {"SAVE","保存"},
        {"INPUT","输入"},
        {"POSITIVE_INTEGER","正整数"},
        {"LOCK","锁定"},
        {"REASON","原因"},
        {"ACCOUNT","帐户"},
        {"CANT_BE_NULL","不可为空"},
        {"MOREOVER",",而且"},
        {"SHOULD_NOT_BE_LESS_THAN","应大于等于"},
        {"DEAL","处理"},
        {"LENGTH_SHOULD_BE_LESS_THAN","长度应该小于等于"},
        {"LOGIN_DATE","登录日期"},
        {"LOGOUT_TIME","注销时间"},
        {"ONLINE_MINUTES","在线时间(分钟)"},
        {"PROG_CODE","程序代码"},
        {"PROG_VALUE","程序"},
        {"PROG_NAME","程序名称"},
        {"SYS_CODE","子系统代码"},
        {"RUN_DATE","运行日期"},
        {"RUN_TIME","运行时间"},
        {"DROP_DATE","断线日期"},
        {"DROP_TIME","断线时间"},
        {"DROPPED_USER_NAME","被断用户名称"},
        {"DROPPED_USER_UNIQUE_NO","被断用户唯一号"},
        {"SCHEDULE_NO","任务号"},
        {"SCHEDULE_NAME","任务名称"},
        {"LOG_TYPE","日志类别"},
        {"LOG_DATE","记录日期"},
        {"LOG_TIME","记录时间"},
        {"REPORT_CODE","报表代码"},
        {"REPORT_NAME","报表名称"},
        {"CREATE_TIME","创建时间"},
        {"CREATE_DATE","创建日期"},
        {"ZH","(中)"},
        {"EN","(英)"},
        {"PROG_PARAMS","程序参数"},
        {"PROG_CODE_FATHER","属于"},
        {"PROG_LEVEL","程序级别"},
        {"CHECK_RIGHT","授权访问"},
        {"RST_URL","结果集地址"},
        {"MEND_FLAG","可修改"},
        {"OPER_FLAG","查询程序"},
        {"NODE_FLAG","菜单结点"},
        {"PICK","选取"},
        {"MENU_CODE","菜单代码"},
        {"MENU_NAME","菜单名称"},
        {"MENU_CODE_FATHER","父菜单代码"},
        {"MENU_LEVEL","菜单级别"},
        {"MENU_INDEX","菜单顺序号"},
        {"LEAF_FLAG","叶子"},
        {"PROG_SYS_CODE","程序所属系统代码"},
        {"NO_MODIFY","禁止修改"},
        {"NO_DEL","禁止删除"},
        {"PROG","程序"},
        {"ROLE","角色"},
        {"SAM3110","该角色拥有以下程序"},
        {"SAM3120","请新增程序"},
        {"SAM3210","该职位拥有以下角色"},
        {"SAM3211","请新增角色"},
        {"SAM3220","该职位拥有以下程序"},
        {"SAM3330","该用户拥有以下职位权限"},
        {"SAM3320","该用户拥有以下角色"},
        {"SAM3310","该用户拥有以下程序"},
        {"SAM3350","该用户权限"},
        {"GENERATE","生成"},
        {"BODY_NAME","用户名称"},
        {"BODY_CODE","用户代码"},
        {"BODY_TYPE","用户类型"},
        {"PUR","供应商"},
        {"ORD","客户"},
        {"HRM","职员"},
        {"GUEST","过客"},
        {"DEPT_NAME","部门名称"},
        {"POSITION_NAME","职位名称"},
        {"ROLE_NAME","角色名称"},
        {"AUTH_FLAG","授权标识"},
        {"POSITION","职位"},
        {"PROG_RIGHT","权限"},
        {"UPDATED_USER","变更用户"},
        {"ALL_USER","所有用户"},
        {"CONFIRM_PASSWORD","确认密码"},
        {"PASS_MENDABLE","密码可修改"},
        {"PERMIT_NUM","允许数量"},
        {"IP_ADDR","IP地址"},
        {"USER_STATUS","帐号状态"},
        {"OWN_RIGHT","拥有权限"},
        {"PREVIEW_USER_MENU","预览用户菜单"},
        {"UPDATE_USER_RIGHT","更新用户权限"},
        {"UPDATE_USER_RIGHT_FORCELY","强制更新用户权限"},
        {"TABLE_NAME","表名"},
        {"TOOLS","工具"},
        {"ORDER","顺序号"},
        {"NAME","名称"},
        {"CODE","代码"},
        {"DB","数据库"},
        {"USER","用户"},
        {"TYPE","类型"},
        {"DRIVER_MANAGER","驱动管理器"},
        {"OS","操作系统"},
        {"MSG","消息"},
        {"DESC","描述"},
        {"PROCESS","处理"},
        {"LEVEL","级别"},
        {"REMARKS","备注"},
        {"START","开始"},
        {"WORK","工作"},
        {"LOG","记录"},
        {"TIME_OUT","页面超时(分)"},
        {"MUST_BE_LESS_THAN","必须小于"},
        {"DEPT","部门"},
        {"BRIEF","简称"},
        {"DEPT_CODE_FATHER","上级部门代码"},
        {"DEPT_NAME_FATHER","上级部门名称"},
        {"MASTER","主管"},
        {"DEPT_RECURSIVE","部门级别循环定义"},
        {"FIELD_HEAD","标题头"},
        {"ORDER","顺序号"},
        {"VISIBILITY","可见"},
        {"ORDER_BY","排序"},
        {"IS_FIXED","固定"},
        {"FIELD","字段"},
        {"AUTH_ED","已认证"},
        {"NOT_AUTH_ED","未认证"},
        {"NOT_NEED_AUTH","不需认证"},
        {"PART_FLAG","兼职标识"},
        {"PART_WORK","兼职"},
        {"FINISH","完成"},
        {"",""},
        {"",""}
      };
  public Object[][] getContents() {
        return contents;
  }
}