package com.huiton.cerp.login;
import java.util.*; 
/**
 * Title:        CERP测试框架
 * Description: 资源文件
 * Copyright:    Copyright (c) 2000
 * Company:      BRITC
 * @author zaj
 * @version 1.0
 */
 
public class LoginRes_en extends java.util.ListResourceBundle{
    static final Object[][] contents = new String[][]{
        { "ABOUT", " About " },
        { "PRINT"," Print "},
        { "TONGUE"," Chinese "},
        { "EXIT"," Exit "},
        { "WANT_EXIT"," Do you really want to exit? "},
        { "HELP"," Help "},
        { "COMPANY"," Company "},
        { "COPYRIGHT"," Copyright "},
        { "VERSION"," Version "},
        { "WELCOME"," Welcome "},
        { "LOGIN"," Login "},
        { "COMPANY_NAME"," Company "},
        { "USER_NAME"," User name "},
        { "USER_CODE"," User code "},
        { "USER_UNIQUE_NO"," User unique no "},
        { "USER_IP"," User IP "},
        { "LOGIN_TIME"," Login time"},
        { "OFFLINE"," Off-line "},
        { "PASSWORD"," Password "},
        { "PASSWD"," Change password "},
        { "YEAR"," Year "},
        { "LENGTH_SHOULD_BETWEEN"," Its length must be between "},
        { "AND"," and "},
        { "SCOPE"," "},
        { "YEAR_SHOULD_BE_4_DIGITS"," The length of year must be 4 "},
        { "RELOGIN"," Relogin "},
        { "SET"," Set "},
        { "SUCCEED"," Successfully "},
        { "FAILED"," failed "},
        {"COPYRIGHT_INF"," 2001-2020 "},
        {"VERSION_INF"," CERP e-ERP "},
        {"NO_USER"," No such user "},
        {"WRONG_PASSWORD"," Wrong password "},
        {"DB_ERROR"," Database connection failed, please wait for a while "},
        {"UNKNOWN_ERROR"," Internal server error "},
        {"NO_YEAR"," No such year "},
        {"IP_FORBID"," Forbidden IP "},
        {"STATUS_FORBID"," Forbidden user "},
        {"USER_OVERFLOW"," Too many users use the same account  "},
        {"COMPANY_USER_OVERFLOW"," Too many users in the company "},
        {"OLD_PASSWORD"," Old password "},
        {"NEW_PASSWORD"," New password "},
        {"REVIEW_NEW_PASSWORD"," Verify new password "},
        {"SUBMIT"," Submit "},
        {"RESET"," Reset "},
        {"PASSWD_SUCCEED"," Password changed successfully "},
        {"PASSWD_FAILED"," Failed to change the password"},
        {"PASSWD_NOT_MATCH"," Wrong old password "},
        {"PASSWD_DB_ERROR"," Useer doesn't exist, "},
        {"PASSWD_IS_FORBID"," Forbid to change password！"},
        {"MUST_EQUAL"," Must equal to "},
        {"MY_FAVOR","My favorite"},
        {"QUERY"," Query "},
        {"WANT_DEL","  Really want to delete the selected record(s)? "},
        {"WANT_DEL_ALL","  Really want to delete all matched record(s)? "},
        {"QUERY_STYLE"," Query condition "},
        {"CONDITION"," Condition "},
        {"SELECT_PAGE"," Select all the page"},
        {"SELECT_ALL"," All "},
        {"DELETE"," Delete "},
        {"MODIFY"," Modify "},
        {"UPDATE"," Update "},
        {"VIEW"," Browse "},
        {"NEW"," New "},
        {"OPERATION"," Operation "},
        {"FAVOR_TYPE"," Favorite type "},
        {"FAVOR_NAME"," Favorite name "},
        {"PROG_NAME"," Program name "},
        {"SEQ_NO"," Sequence no "},
        {"BACK"," Back "},
        {"PARAMS_WRONG"," Wrong parameters "},
        {"CLOSE"," Close "},
        {"DUPLICATE_KEY"," Duplicate primary key "},
        {"RECORD_EXISTS"," The page is added to your favorite before! "},
        {"PLEASE"," Please "},
        {"CHOOSE"," Choose "},
        {"START_STOP_TIME"," Duration "},
        {"EVENT_TYPE"," Event type "},
        {"LOCATION"," Location "},
        {"SUBJECT"," Subject "},
        {"MORE"," more... "},
        {"DAILY"," Daily "},
        {"WEEKLY"," Weekly"},
        {"MONTHLY"," Monthly "},
        {"DATE"," Date "},
        {"START_TIME"," Beginning time "},
        {"STOP_TIME"," End time "},
        {"SUBJECT"," Subject"},
        {"LOCATION"," Location "},
        {"EVENT_TYPE"," Event type "},
        {"PRIV_FLAG"," Private "},
        {"DEAL_FLAG"," Completed "},
        {"EVENT_DESC"," Event disc "},
        {"DEAL_DESC"," Operation Desc "},
        {"SAVE_BACK"," Save and  return "},
        {"SAVE_CONTINUE"," Save and continue "},
        {"SAVE"," Save "},
        {"INPUT"," input "},
        {"POSITIVE_INTEGER"," Positive integer "},
        {"LOCK"," Lock "},
        {"ACCOUNT"," Account "},
        {"REASON"," Reason "},
        {"CANT_BE_NULL"," can't be null "},
        {"MOREOVER",", and "},
        {"SHOULD_NOT_BE_LESS_THAN"," must be greater than "},
        {"DEAL"," Disposal "},
        {"LENGTH_SHOULD_BE_LESS_THAN"," its length must be less than "},
        {"LOGIN_DATE"," Login date "},
        {"LOGOUT_TIME"," Logout time "},
        {"ONLINE_MINUTES"," Online minutes"},
        {"PROG_CODE"," Program code "},
        {"PROG_VALUE"," Program "},
        {"PROG_NAME"," Program name "},
        {"SYS_CODE"," System code "},
        {"RUN_DATE"," Run date "},
        {"RUN_TIME"," Run time "},
        {"DROP_DATE"," Drop date "},
        {"DROP_TIME"," Drop time "},
        {"DROPPED_USER_NAME"," Dropped user name "},
        {"DROPPED_USER_UNIQUE_NO"," Drop user unique no "},
        {"SCHEDULE_NO"," Schedule no "},
        {"SCHEDULE_NAME"," Schedule name "},
        {"LOG_TYPE"," Log type"},
        {"LOG_DATE"," Log date "},
        {"LOG_TIME"," Log time "},
        {"REPORT_CODE"," Report code "},
        {"REPORT_NAME"," Report name "},
        {"CREATE_TIME"," Create time "},
        {"CREATE_DATE"," Create date "},
        {"ZH","(Zh)"},
        {"EN","(En)"},
        {"PROG_PARAMS"," Program params"},
        {"PROG_CODE_FATHER"," Attachment to "},
        {"PROG_LEVEL"," Program level "},
        {"CHECK_RIGHT"," Protected "},
        {"RST_URL"," Resultset URL "},
        {"MEND_FLAG"," Editable "},
        {"OPER_FLAG"," Query "},
        {"NODE_FLAG"," Node "},
        {"PICK"," Choose "},
        {"MENU_CODE"," Menu code "},
        {"MENU_NAME"," Menu name "},
        {"MENU_CODE_FATHER"," Attachment to "},
        {"MENU_LEVEL"," Menu level "},
        {"MENU_INDEX"," Menu index "},
        {"LEAF_FLAG"," Leaf "},
        {"PROG_SYS_CODE"," Program's system code "},
        {"NO_MODIFY"," No modify "},
        {"NO_DEL"," No delete "},
        {"PROG"," Program "},
        {"ROLE"," Role "},
        {"SAM3110"," The role owns programs "},
        {"SAM3120"," Please add programs "},
        {"SAM3210"," The position owns roles "},
        {"SAM3211"," Please add roles "},
        {"SAM3220"," The position owns programs "},
        {"SAM3330"," The user owns positions' right "},
        {"SAM3320"," The user owns roles "},
        {"SAM3310"," The user owns programs "},
        {"SAM3350"," The user's right "},
        {"GENERATE"," Generate "},
        {"BODY_NAME"," User name "},
        {"BODY_CODE"," USer code "},
        {"BODY_TYPE"," User type "},
        {"PUR"," PUR "},
        {"ORD"," ORD "},
        {"HRM"," Employee "},
        {"GUEST"," Guest "},
        {"DEPT_NAME"," Dept name "},
        {"POSITION_NAME"," Position name "},
        {"ROLE_NAME"," Role name "},
        {"AUTH_FLAG"," Auth flag "},
        {"POSITION"," Position "},
        {"PROG_RIGHT"," Prog right "},
        {"UPDATED_USER"," updated users' "},
        {"ALL_USER"," all users' "},
        {"CONFIRM_PASSWORD"," Confirm password "},
        {"PASS_MENDABLE","密码可修改"},
        {"PERMIT_NUM","允许数量"},
        {"IP_ADDR","IP地址"},
        {"USER_STATUS","帐号状态"},
        {"OWN_RIGHT"," Owns right "},
        {"PREVIEW_USER_MENU"," Preview user's menu "},
        {"UPDATE_USER_RIGHT"," Update user's right "},
        {"UPDATE_USER_RIGHT_FORCELY"," Update user's right forcely "},
        {"TABLE_NAME"," Table name "},
        {"TOOLS"," Tools "},
        {"ORDER"," order "},
        {"NAME"," name "},
        {"CODE"," code "},
        {"DB"," Database "},
        {"USER"," User "},
        {"TYPE"," type "},
        {"DRIVER_MANAGER"," Driver manager "},
        {"OS"," Operation system "},
        {"MSG"," Message "},
        {"DESC"," desc "},
        {"PROCESS"," process "},
        {"LEVEL"," level "},
        {"REMARKS"," Remarks "},
        {"START"," Start "},
        {"WORK"," Work "},
        {"LOG"," Log "},
        {"TIME_OUT"," Time out(minute(s)) "},
        {"MUST_BE_LESS_THAN"," must be less than "},
        {"DEPT"," Dept "},
        {"BRIEF"," brief "},
        {"DEPT_CODE_FATHER"," Parent's code "},
        {"DEPT_NAME_FATHER"," Parent's name "},
        {"MASTER"," Master "},
        {"DEPT_RECURSIVE"," Dept's rank is recursive "},
        {"FIELD_HEAD"," Field headline "},
        {"ORDER"," Order "},
        {"VISIBILITY"," Visibility "},
        {"ORDER_BY"," Order by "},
        {"IS_FIXED"," Fixed "},
        {"FIELD"," Field "},
        {"AUTH_ED"," Authenticated"},
        {"NOT_AUTH_ED"," Not authenticated "},
        {"NOT_NEED_AUTH"," Not need authenticate"},
        {"PART_FLAG"," Part work "},
        {"PART_WORK"," Part work "},
        {"FINISH"," Finish "},
        {"",""}
      };
  public Object[][] getContents() {
        return contents;
  }
}