/*
 * CurrentFloorPanel.java
 *
 * Created on 2006年1月5日, 下午 1:08
 */

package marsping;

import marsping.component.Elevator;
import marsping.component.type.Floor;

/**
 *
 * @author  MarsPing
 */
public class CurrentFloorPanel extends javax.swing.JPanel {
    FloorPanel[] floorPanel = new FloorPanel[Floor.values().length];
    
    /** Creates new form CurrentFloorPanel */
    public CurrentFloorPanel() {
        initComponents();
        Floor[] floors = Floor.values();
        for(int i=0; i<floorPanel.length; i++)
            floorPanel[i] = new FloorPanel(floors[i]);
        
        for(FloorPanel fp:floorPanel)
            add(fp, 0);
    }
    
    public void setAllPanel(){
        for(FloorPanel fp:floorPanel)
            fp.resetPanel();
        floorPanel[Elevator.getCurrentFloor().ordinal()].setPanel();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        setPreferredSize(new java.awt.Dimension(60, 365));
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
