/*
 * FloorPanel.java
 *
 * Created on 2006年1月5日, 下午 12:42
 */

package marsping;

import marsping.component.type.Floor;

/**
 *
 * @author  MarsPing
 */
public class FloorPanel extends javax.swing.JPanel {
    Floor floor;
    
    /** Creates new form FloorPanel */
    public FloorPanel(Floor f) {
        floor = f;
        initComponents();
    }
    
    public void setPanel(){
        setBackground(new java.awt.Color(153, 255, 153));
    }
    
    public void resetPanel(){
        setBackground(new java.awt.Color(204, 204, 204));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        floorLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setName("");
        setPreferredSize(new java.awt.Dimension(40, 40));
        floorLabel.setFont(new java.awt.Font("Dialog", 1, 19));
        floorLabel.setText(floor.toString());
        add(floorLabel);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel floorLabel;
    // End of variables declaration//GEN-END:variables
    
}
