/*
 * ListPanel.java
 *
 * Created on 2006年1月5日, 下午 2:22
 */
package marsping;

import marsping.component.ElevatorController;
import marsping.component.data.CallList;
/**
 *
 * @author  MarsPing
 */
public class ListPanel extends javax.swing.JPanel {
    private ElevatorController controller;
    
    /** Creates new form ListPanel */
    public ListPanel(ElevatorController controller) {
        this.controller = controller;
        initComponents();
    }
    
    public void setList(CallList up, CallList down) {
        upList.setText(up.toString());
        downList.setText(down.toString());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        upLabel = new javax.swing.JLabel();
        downLabel = new javax.swing.JLabel();
        downPanel = new javax.swing.JScrollPane();
        downList = new javax.swing.JTextArea();
        upPanel = new javax.swing.JScrollPane();
        upList = new javax.swing.JTextArea();

        upLabel.setText("UP");

        downLabel.setText("DOWN");

        downPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        downPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        downList.setColumns(20);
        downList.setEditable(false);
        downList.setRows(5);
        downList.setText("First:\nBuffer:");
        downPanel.setViewportView(downList);

        upPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        upPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        upList.setColumns(20);
        upList.setEditable(false);
        upList.setRows(5);
        upList.setText("First:\nBuffer:");
        upPanel.setViewportView(upList);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(downLabel)
                    .add(upLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(upPanel)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, downPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {downPanel, upPanel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(upLabel)
                    .add(upPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(8, 8, 8)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(downLabel)
                    .add(downPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        layout.linkSize(new java.awt.Component[] {downPanel, upPanel}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel downLabel;
    private javax.swing.JTextArea downList;
    private javax.swing.JScrollPane downPanel;
    private javax.swing.JLabel upLabel;
    private javax.swing.JTextArea upList;
    private javax.swing.JScrollPane upPanel;
    // End of variables declaration//GEN-END:variables
    
}
