package com.huiton.cerp.sam;

/**
 * Title:
 * Description:
 * Copyright:    Copyright (c) 2001
 * Company:      BRITC
 * @author       黄岳
 * @version      1.0
 */

import java.util.*;

public class SamRes extends java.util.ListResourceBundle {
  static final Object[][] contents = new String[][]{
        //以下由黄岳定义
        { "CODE","代码"},
        { "NAME","名称"},
        { "OPERATION","操作"},
        { "DELETE","删除"},
        { "ADD","增加"},
        { "UPDATE","修改"},
        { "CONFIRM_UPDATE","修改确认"},
        { "RESET","重置"},
        { "THE","第"},
        { "TOGETHER","共"},
        { "PAGE","页"},
        { "CURRENT_RECORD_BEING_USED_CAN'T_DELETE","当前记录正在被使用，不可删除!"},
        { "QUERY_CONDITION","查询条件"},
        { "QUERY","查询"},
        { "RECORD_ERROR","录入错误，建议输入3个以内数字或字符!"},
        { "CURRENT_SYSTEM_CAN'T_DELETE","该系统已有程序,不可删除!"},
        { "CONDITION","条件"},
        { "PLEASE_INPUTE_MODE_OF_QUERY","请选择查询方式!"},
        { "CURRENT_RECORD_CAN'T_UPDATE","该记录不可修改!"},
        { "MODE_OF_QUERY","查询方式"},
        { "PROGRAM","程序"},
        { "PROGRAM_CODE","程序代码"},
        { "PROGRAM_NAME","程序名称"},
        { "SAVE_AND_RETURN","保存返回"},
        { "SAVE","保存"},
        { "CLEAR","清空"},
        { "RETURN","返回"},
        { "REMARK","备注"},
        { "CURRENT_RECORD_EXIST","该记录已经存在！"},
        { "SHOW_ORDER","显示顺序"},
        { "CHOOSE","选择"},
        { "SELECTED","选用"},
        { "MENU","菜单"},
        { "USER_ATTESTATION_MANAGE","用户认证管理"},
        { "USER_UNIQUE_CODE","用户唯一号"},
        { "USER_CODE","用户代码"},
        { "USER_IP_ADDR","用户iP地址"},
        { "USER_ACCOUNT_STATE","用户帐号状态"},
        { "ALLOW_CURRENT_NUM","允许并发数"},
        { "IF_PASSWORD_MAINTENANCE","密码可否维护"},
        { "PASSWORD_DIFFER","输入密码不一致!"},
        { "PASSWORD","密码"},
        { "CONFIRM_PASSWORD","确认密码"},
        { "AVAILABILITY","有效"},
        { "INVALIDATION","无效"},
        { "YES","是"},
        { "NO","否"},
        { "CANCEL","取消"},
        { "PLEASE_INPUTE_PAGE_NUMBER","请输入页数！"},
        { "POSITION","职位"},
        { "SUPERIOR_POSITION","上级职位"},
        { "DEPT_CODE","部门代码"},
        { "POSITION_CODE","职位代码"},
        { "POSITION_NAME","职位名称"},
        { "STRAIGHT_CHARGE_DEPT_CODE","直接主管部门代码"},
        { "STRAIGHT_CHARGE_POSITION_CODE","直接主管职位代码"},
        { "DEFINED_SUPERIOR_DEPT_NOT_EXIST","您所定义上级部门不存在!"},
        { "THE_DEPT_CAN'T_DELETE","该部门不可删除!"},
        { "CURRENT_RECORD_EXIST","该记录已经存在！"},
        { "PLEASE_INPUTE_CONDITION_OF_QUERY","请输入查询条件!"},
        { "USER_NAME","用户名称"},
        { "USER_TYPE","用户类型"},
        { "TEL","电话"},
        { "FAX","传真"},
        { "INNER_MAIL","内部邮址"},
        { "OUTER_MAIL","外部邮址"},
        { "USER_UNIQUE_CODE","用户唯一号"},
        { "PROVIDE_QUOTIENT","供应商"},
        { "CUSTOMER","客户"},
        { "STAFFER","职员"},
        { "CLASS","分类"},
        { "COMMUNICATION_ADDR","通信地址"},
        { "MAIL_ADDR_INPUTE_ERRO","mail地址输入错误!"},
        { "NEXT","下一步"},
        { "USER_INFORMATION","用户信息"},
        { "PLURALITY_FLAG","兼职标记"},
        { "NO_PLURALITY","不兼职"},
        { "PLURTALITY","兼职"},
        //公司定义
        { "COMPANY_GROUP_CODE","集团公司代码"},
        { "COMPANY_CODE","公司代码"},
        { "FOR_SHORT","简称"},
        { "ENGLISH_NAME","英文名称"},
        { "ENGLISH_FOR_SHORT","英文简称"},
        { "GENERAL_MANAGE","总经理"},
        { "FINANCE_MAJORDOMO","财务总监"},
        { "LOCAL_MONEY","本位币"},
        { "BANK_OF_OPEN_ACCOUNT","开户行"},
        { "ACCOUNTS","帐号"},
        { "POSTCODE","邮编"},
        { "ENGLISH_ADDR","英文地址"},
        //部门定义
        { "上级部门代码","上级部门代码"},
        { "部门名称","部门名称"},
        { "部门主管职位","部门主管职位"},
        { "上级部门","上级部门"},
        { "部门正在使用","该部门正在使用,不可删除!"},
        { "已有上级部门","录入错误!该下级部门已有上级部门!"},
        { "上级部门是该部门的下级","录入错误!新增上级部门是该部门的下级!"},
        { "上下级相同或为空","录入错误! 录入上下级相等或为空!"},
        { "添加错误","添加错误，重试!"},
        //部门选择
        { "部门选择","部门选择"},
        //职位定义
        { "不可删除","该职位已定义职位关系，若准备删除，请先删除职位关系！"},
        //职位关系定义
        { "上级","上级"},
        { "下级","下级"},
        { "全部上级","全部上级"},
        { "全部下级","全部下级"},
        { "下级职位代码","下级职位代码"},
        { "下级职位名称","下级职位名称"},
        { "下级职位是上级职位的上级","新修改的下级职位是上级职位的上级"},
        { "下级职位已有上级","新增下级职位已有上级"},
        { "录入错误","录入错误"},
        { "修改将把下级的职位关系删掉","修改时会将新下级的职位关系删掉,确认修改吗?"},
        //职位选择
        { "职位选择","职位选择"},
        //职员定义
        { "部门","部门"},
        { "认证","认证"},
        { "已认证","已认证"},
        { "未认证","未认证"},
        { "不需认证","不需认证"},
        { "职员代码","职员代码"},
        { "职员名称","职员名称"},
        { "家庭地址","家庭地址"},
        { "该用户不可删除","该用户不可删除!"},
        { "姓名","姓名"},
        { "所属部门","所属部门"},
        { "是否兼职","是否兼职"},
        { "需要认证标识","需要认证标识"},
        { "稍后申请","申请人数太多,请稍后申请!"},
        { "增加重复","错误,增加重复!"},
        { "用户已经存在","录入错误!用户已经存在!"},
        { "保存继续","保存继续"},
        //兼职定义
        { "用户的本职职位","不可添加,该职位是用户的本职工作!"},
        { "上一步","上一步"},
        //报表申请
        { "报表代码","报表代码"},
        { "报表名称","报表名称"},
        { "当页全选","当页全选"},
        { "全选","全选"},
        { "取消订阅","取消订阅"},
        { "订阅","订阅"},
        { "删除失败","删除失败"},
        { "选择后再取消","请选择后再取消!"},
        { "将报表全部取消吗","确认将报表全部取消吗?"},
        { "将当前页的报表取消吗","确认将当前页的报表取消吗?"},
        { "将选中的报表取消吗","确认将选中的报表取消吗?"},
        { "订阅失败","订阅失败"},
        { "订阅成功","订阅成功"},
        { "选择报表后再订阅","请选择报表后再订阅!"},
        //报表管理
        { "用户唯一号","用户唯一号"},
        { "起始时间","起始时间"},
        { "终止时间","终止时间"},
        { "申请日期","申请日期"},
        { "批准订阅","批准订阅"},
        { "订阅驳回","订阅驳回"},
        { "批准失败","批准失败！"},
        { "否决未生效","否决未生效！"},
        //角色定义
        { "正在使用不可删除","该角色正在使用,不可删除!"},
        { "否决未生效","否决未生效！"},

        //以下王军定义
        { "CURRENCY_DEFINE","币种定义"},
        { "CURRENCY_CODE","币别代码"},
        { "CURRENCY_NAME","币种"},
        { "OPTION","操作"},
        { "DEL","删除"},


        { "ADD","增加"},

        { "ERRORMSG","当前记录已经存在"},

        { "PAGE","页"},
        { "ALTOGETHER","共"},


        { "EVENT_TYPE","事件类型定义"},
        { "EVENT_CODE","事件代码"},
        { "EVENT_NAME","事件类型名"},
        { "INFORM_TYPE","通知类型定义"},
        { "INFORM_CODE","类型代码"},
        { "INFORM_NAME","类型名称"},
        { "INPUT_ERROR_STRING","输入数据中有非法字符"},
        { "ONLY_INPUT_INT_TYPE","请输入数字类型!"},


        { "USER_UNIQUE_NO","用户唯一号"},
        { "USER_NAME","用户名"},
        { "IP_ADDR","用户IP"},
        { "LOGIN_DATE","登录日期"},
        { "LOGIN_TIME","登录时间"},
        { "SELECT_ALL","全选"},
        { "SYS_CODE","子系统"},
        { "PROG_CODE","程序代码"},
        { "PROG_NAME","程序名称"},
        { "RUN_DATE","运行日期"},
        { "SCHEDULE_NO","任务号"},
        { "LOG_TYPE","日志类别"},
        { "RUN_TIME","运行时间"},

        { "CREATE_DATE","日期"},
        { "REPORT_CODE","报表代码"},
        { "REPORT_NAME","报表名称"},
        { "DROPPED_USER_UNIQUE_NO","锁定帐号"},
        { "DROP_DATE","日期"},
        { "ALL_IN_THE_PAGE","当页全选"},
        { "NO_SELECT_DEL_DATA","没有选择删除记录"},
        //zaj added
        {"ROLE_CODE","角色代码"},
        {"ROLE_NAME","角色名称"},
        {"",""}
      };
  public Object[][] getContents() {
    return contents;
  }
}