package com.huiton.cerp.sam;

/**
 * Title:
 * Description:
 * Copyright:    Copyright (c) 2001
 * Company:      BRITC
 * @author       黄岳
 * @version      1.0
 */

import java.util.*;

public class SamRes_en extends java.util.ListResourceBundle {
  static final Object[][] contents = new String[][]{
        //以下由黄岳定义
        { "CODE","Code"},
        { "NAME","Name"},
        { "OPERATION","Operation"},
        { "DELETE","Delete"},
        { "ADD","Add"},
        { "UPDATE","Update"},
        { "CONFIRM_UPDATE","Confirm update"},
        { "RESET","Reset"},
        { "THE","The"},
        { "TOGETHER","Together"},
        { "PAGE","Page"},
        { "CURRENT_RECORD_BEING_USED_CAN'T_DELETE","Current Record Being Used,Can't Be delete!"},
        { "QUERY_CONDITION","Query Condition"},
        { "QUERY","Query"},
        { "RECORD_ERROR","Record Error,Advice To Inpute Less Three Figure Or Character"},
        { "CURRENT_SYSTEM_CAN'T_DELETE","Current System Have Program,Can't Delete!"},
        { "CONDITION","Condition"},
        { "PLEASE_INPUTE_MODE_OF_QUERY","Please Inpute Mode Of Query"},
        { "CURRENT_RECORD_CAN'T_UPDATE","Current Record Can't Update"},
        { "MODE_OF_QUERY","Mode Of Query"},
        { "PROGRAM","Program"},
        { "PROGRAM_CODE","Program Code"},
        { "PROGRAM_NAME","Program Name"},
        { "SAVE_AND_RETURN","Save and Return"},
        { "SAVE","Save"},
        { "CLEAR","Clear"},
        { "RETURN","Return"},
        { "REMARK","Rmark"},
        { "CURRENT_RECORD_EXIST","Current Record Exist"},
        { "SHOW_ORDER","Show Order"},
        { "CHOOSE","Choose"},
        { "SELECTED","Selected"},
        { "MENU","Menu"},
        { "USER_ATTESTATION_MANAGE","User Attestation manage"},
        { "USER_UNIQUE_CODE","User Unique Code"},
        { "USER_CODE","User Code"},
        { "USER_IP_ADDR","User Ip Addr"},
        { "USER_ACCOUNT_STATE","User Account State"},
        { "ALLOW_CURRENT_NUM","Allow Current Num"},
        { "IF_PASSWORD_MAINTENANCE","Ip Password Maintenance"},
        { "PASSWORD_DIFFER","Password Differ!"},
        { "PASSWORD","Password"},
        { "CONFIRM_PASSWORD","Confirm Password"},
        { "AVAILABILITY","Availability"},
        { "INVALIDATION","Invalidation"},
        { "YES","Yes"},
        { "NO","No"},
        { "CANCEL","Cancel"},
        { "PLEASE_INPUTE_PAGE_NUMBER","Please Inpute Page Number！"},
        { "POSITION","Position"},
        { "SUPERIOR_POSITION","Superior Position"},
        { "DEPT_CODE","Dept Code"},
        { "POSITION_CODE","Position Code"},
        { "POSITION_NAME","Position Name"},
        { "STRAIGHT_CHARGE_DEPT_CODE","Straigth Charge Dept Code"},
        { "STRAIGHT_CHARGE_POSITION_CODE","Straigth Charge Position Code"},
        { "DEFINED_SUPERIOR_DEPT_NOT_EXIST","Defined Superior Dept Not Exist!"},
        { "THE_DEPT_CAN'T_DELETE","The Dept Can't Delete!"},
        { "CURRENT_RECORD_EXIST","Current Record Exist"},
        { "PLEASE_INPUTE_CONDITION_OF_QUERY","Please Inpute Condition Of Query!"},
        { "USER_NAME","User Name"},
        { "USER_TYPE","User Type"},
        { "TEL","Tel"},
        { "FAX","Fax"},
        { "INNER_MAIL","Inner Mail"},
        { "OUTER_MAIL","Outer Mail"},
        { "USER_UNIQUE_CODE","User Unique Code"},
        { "PROVIDE_QUOTIENT","Provide Quotient"},
        { "CUSTOMER","Customer"},
        { "STAFFER","Staffer"},
        { "CLASS","Class"},
        { "COMMUNICATION_ADDR","Addr"},
        { "MAIL_ADDR_INPUTE_ERRO","Mail Addr Inpute Erro!"},
        { "NEXT","Next"},
        { "USER_INFORMATION","User Information"},
        { "PLURALITY_FLAG","Plurality"},
        { "NO_PLURALITY","No Plurality"},
        { "PLURTALITY","Plurality"},
        { "COMPANY_GROUP_CODE","Company group code"},
        { "COMPANY_CODE","Company code"},
        { "FOR_SHORT","For short"},
        { "ENGLISH_NAME","English name"},
        { "ENGLISH_FOR_SHORT","English for short"},
        { "GENERAL_MANAGE","General manage"},
        { "FINANCE_MAJORDOMO","Finance majordomo"},
        { "LOCAL_MONEY","Local money"},
        { "BANK_OF_OPEN_ACCOUNT","Bank of open account"},
        { "ACCOUNTS","accounts"},
        { "POSTCODE","Postcode"},
        { "ENGLISH_ADDR","English address"},
        { "上级部门代码","Superior dept code "},
        { "部门名称","Dept name"},
        { "部门主管职位","Dept charge Position"},
        { "上级部门","Superior dept"},
        { "部门正在使用","The dept is be using,don't delte!"},
        { "已有上级部门","Inpute Error,the superior dept of the junior is exied!"},
        { "上级部门是该部门的下级","Inpute Error,new superior dept is the junior of dept!"},
        { "上下级相同或为空","Inpute Error,depts inputed is equal or null!"},
        { "添加错误","Add error!"},
         //部门选择
        { "部门选择","Select dept"},
        //职位定义
        { "不可删除","The position relation is alread defined,if want to delete,please delete its relation!"},
        //职位关系定义
        { "上级","Superior"},
        { "下级","Junior"},
        { "全部上级","All superior"},
        { "全部下级","All junior"},
        { "下级职位代码","Junior position code"},
        { "下级职位名称","Junior position name"},
        { "下级职位是上级职位的上级","Junior position of update is the superior"},
        { "下级职位已有上级","Junior position of add has alread superior"},
        { "录入错误","Inpute error"},
        { "修改将把下级的职位关系删掉","It will delete relation of new junior position,affirm ?"},
        //职位选择
        { "职位选择","Select position"},
        //职员定义
        { "部门","Dept"},
        { "认证","Attestation"},
        { "已认证","Attested"},
        { "未认证","No Attestation"},
        { "不需认证","Need not Attestation"},
        { "职员代码","Staffer code"},
        { "职员名称","Staffer name"},
        { "家庭地址","Home addr"},
        { "该用户不可删除","The user can't delete!"},
        { "姓名","Name"},
        { "所属部门","Dept belonged to"},
        { "是否兼职","If plurality"},
        { "需要认证标识","The sign of need Attestation"},
        { "稍后申请","Proposer is much morn,please wait!"},
        { "增加重复","Add repeat!"},
        { "用户已经存在","User alread exied!"},
        { "保存继续","Save continue"},
        //兼职定义
        { "用户的本职职位","Don't add,the position is selfpositin"},
        { "上一步","Up"},
        //报表申请
        { "报表代码","Report forms code"},
        { "报表名称","Report forms name"},
        { "当页全选","Select all in current page"},
        { "全选","Select all"},
        { "取消订阅","Subscribe cancel"},
        { "订阅","Subscribe"},
        { "删除失败","Delete error"},
        { "选择后再取消","Please cancel after select!"},
        { "将报表全部取消吗","Confirm cancel all report forms?"},
        { "将当前页的报表取消吗","Confirm cancel current page report forms?"},
        { "将选中的报表取消吗","Confirm cancel selected Report forms?"},
        { "订阅失败","Subscribe false"},
        { "订阅成功","Subscribe succeed"},
        { "选择报表后再订阅","Subscribe report forms after selected!"},
        //报表管理
        { "用户唯一号","Unique No"},
        { "起始时间","Start date"},
        { "终止时间","End date"},
        { "申请日期","Application date"},
        { "批准订阅","Subscribe authorize"},
        { "订阅驳回","Subscribe reject"},
        { "批准失败","Subscribe false！"},
        { "否决未生效","Reject not become effective"},
        //角色定义
        { "正在使用不可删除","The role being using,dong't delete!"},

        { "CURRENCY_DEFINE","currency_define"},
        { "CURRENCY_CODE","currency_code"},
        { "CURRENCY_NAME","currency_name"},
        { "OPTION","option"},
        { "DEL","del"},
        { "UPDATE","update"},
        { "ADD","add"},

        { "ERRORMSG","errorMsg"},


        { "PAGE","page"},
        { "ALTOGETHER","Altogether"},


        { "EVENT_TYPE","event_type"},
        { "EVENT_CODE","event_code"},
        { "EVENT_NAME","event_name"},
        { "INFORM_TYPE","inform_type"},
        { "INFORM_CODE","inform_code"},
        { "INFORM_NAME","inform_name"},
        { "INPUT_ERROR_STRING","input_error_string"},
        { "ONLY_INPUT_INT_TYPE","only input int type"},


         { "USER_UNIQUE_NO","user_unique_no"},
        { "USER_NAME","user_name"},
        { "IP_ADDR","ip_addr"},
         { "LOGIN_DATE","login_date"},
         { "LOGIN_TIME","login_time"},

        { "SELECT_ALL","Select_All"},
        { "SYS_CODE","sys_code"},
         { "PROG_CODE","prog_code"},
         { "PROG_NAME","prog_name"},
        { "RUN_DATE","run_date"},
        { "SCHEDULE_NO","schedule_no"},
        { "LOG_TYPE","log_type"},
        { "RUN_TIME","run_time"},
        { "CREATE_DATE","create_date"},
        { "REPORT_CODE","report_code"},
        { "REPORT_NAME","report_name"},
        { "DROPPED_USER_UNIQUE_NO","dropped_user_unique_no"},
        { "DROP_DATE","drop_date"},
        { "ALL_IN_THE_PAGE","all_in_the_page"},
        { "NO_SELECT_DEL_DATA","no_select_del_data"},
        //zaj added
        {"ROLE_CODE"," Role code "},
        {"ROLE_NAME"," Role name "},
        {"",""}
      };
  public Object[][] getContents() {
    return contents;
  }
}