/***********************************************
   ┏━━━━━━━━━━━━━━━━━━━━━┓
   ┃             源 码 爱 好 者               ┃
   ┣━━━━━━━━━━━━━━━━━━━━━┫
   ┃                                          ┃
   ┃           提供源码发布与下载             ┃
   ┃                                          ┃
   ┃        http://www.codefans.net           ┃
   ┃                                          ┃
   ┃            互助、分享、提高              ┃
   ┗━━━━━━━━━━━━━━━━━━━━━┛
************************************************/
import java.awt.*;

/**
 * 
 * 显示器测试程序
 * 
 * @author fubin www.cujava.com
 *
 */
public class Disp_Prop extends javax.swing.JFrame {
    
    /** Creates new form Disp_Prop */
    int i,j,xpos,ypos;
    Disp_Mode dm;
    DisplayMode tmode;
    public Disp_Prop() {     	
    	GraphicsEnvironment GEn = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice GDevs[] = GEn.getScreenDevices();
        for(i=0;i<1;i++)
        {
                dm = new Disp_Mode(GDevs[i]);
                dm.addMode();
        }   	        
        initComponents();         
        setSliders(0);
        setSliders(1);
        setSliders(2);
        jLabel_Resolution.setText("Width x Height : "+dm.res.get(0).toString());
        jLabel_Depth.setText("Depth : "+dm.bits[0].get(0).toString()+" bpp");
        jLabel_Rate.setText("Rate : "+dm.rrates[0].get(0).toString()+" Hz");
        jLabel_Available.setText("["+dm.res.get(jSlider_Resolution.getValue()).toString()+"] ["+dm.bits[0].get(jSlider_Depth.getValue()).toString()+" bpp] ["+dm.rrates[0].get(jSlider_Rate.getValue()).toString()+" Hz]");
        jLabel_System.setText("["+dm.orgDm.getWidth()+" x "+dm.orgDm.getHeight()+"] ["+dm.orgDm.getBitDepth()+" bpp] ["+dm.orgDm.getRefreshRate()+" Hz]");        
        dm.GDev.setFullScreenWindow(this);
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Ico.png")).getImage());      
        //this.setLocation(200,150);
        this.setSize(391,453+35);    
        //this.setExtendedState(java.awt.Frame.NORMAL);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jSlider_Resolution = new javax.swing.JSlider();
        jLabel_Resolution = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSlider_Depth = new javax.swing.JSlider();
        jLabel_Depth = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSlider_Rate = new javax.swing.JSlider();
        jLabel_Rate = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton_Test = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_Reset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel_Available = new javax.swing.JLabel();
        jLabel_Applied = new javax.swing.JLabel();
        jLabel_System = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Show Test www.cujava.com");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Resolution", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));
        jSlider_Resolution.setMajorTickSpacing(1);
        jSlider_Resolution.setMaximum(1);
        jSlider_Resolution.setPaintTicks(true);
        jSlider_Resolution.setSnapToTicks(true);
        jSlider_Resolution.setValue(0);
        jSlider_Resolution.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_ResolutionStateChanged(evt);
            }
        });

        jPanel1.add(jSlider_Resolution);
        jSlider_Resolution.setBounds(80, 40, 230, 30);

        jLabel_Resolution.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Resolution.setText("Width x Height : ");
        jPanel1.add(jLabel_Resolution);
        jLabel_Resolution.setBounds(80, 20, 210, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resolution.png")));
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setIconTextGap(0);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 20, 60, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 130, 330, 80);

        jPanel2.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Bit Depth", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));
        jSlider_Depth.setMajorTickSpacing(1);
        jSlider_Depth.setMaximum(0);
        jSlider_Depth.setPaintTicks(true);
        jSlider_Depth.setSnapToTicks(true);
        jSlider_Depth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_DepthStateChanged(evt);
            }
        });

        jPanel2.add(jSlider_Depth);
        jSlider_Depth.setBounds(60, 40, 80, 30);

        jLabel_Depth.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Depth.setText("Depth :");
        jPanel2.add(jLabel_Depth);
        jLabel_Depth.setBounds(60, 20, 80, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bit.png")));
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setIconTextGap(0);
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 20, 40, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 220, 150, 80);

        jPanel3.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Refresh Rate", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));
        jSlider_Rate.setMajorTickSpacing(1);
        jSlider_Rate.setMaximum(0);
        jSlider_Rate.setPaintTicks(true);
        jSlider_Rate.setSnapToTicks(true);
        jSlider_Rate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_RateStateChanged(evt);
            }
        });

        jPanel3.add(jSlider_Rate);
        jSlider_Rate.setBounds(60, 40, 100, 30);

        jLabel_Rate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Rate.setText("Rate :");
        jPanel3.add(jLabel_Rate);
        jLabel_Rate.setBounds(60, 20, 90, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rate.png")));
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel15.setIconTextGap(0);
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 20, 40, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(190, 220, 170, 80);

        jButton_Test.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Test.png")));
        jButton_Test.setText("Test");
        jButton_Test.setToolTipText("Press to set current settings.");
        jButton_Test.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton_Test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TestActionPerformed(evt);
            }
        });

        getContentPane().add(jButton_Test);
        jButton_Test.setBounds(50, 410, 80, 30);

        jButton_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit.png")));
        jButton_Exit.setText("Exit");
        jButton_Exit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        getContentPane().add(jButton_Exit);
        jButton_Exit.setBounds(260, 410, 80, 30);

        jPanel4.setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "About", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eMac (Side).png")));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setIconTextGap(0);
        jPanel4.add(jLabel1);
        jLabel1.setBounds(20, 20, 80, 80);

        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Display Resolution Test Application");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel2);
        jLabel2.setBounds(120, 20, 200, 14);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Author :  Samir Solanki [SAMSOL]");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel3);
        jLabel3.setBounds(120, 40, 200, 14);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Language : JDK 1.6");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel4);
        jLabel4.setBounds(120, 60, 200, 14);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Contact : solanki.samir@gmail.com");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel5);
        jLabel5.setBounds(120, 80, 200, 14);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(30, 10, 330, 110);

        jButton_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png")));
        jButton_Reset.setText("Reset");
        jButton_Reset.setToolTipText("Press to set system settings.");
        jButton_Reset.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetActionPerformed(evt);
            }
        });

        getContentPane().add(jButton_Reset);
        jButton_Reset.setBounds(150, 410, 90, 30);

        jPanel5.setLayout(null);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Display Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("System :");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(80, 60, 50, 20);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Available :");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(60, 20, 70, 20);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Applied :");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(80, 40, 50, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setting.png")));
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setIconTextGap(0);
        jPanel5.add(jLabel12);
        jLabel12.setBounds(10, 20, 60, 60);

        jLabel_Available.setForeground(new java.awt.Color(0, 102, 0));
        jLabel_Available.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel5.add(jLabel_Available);
        jLabel_Available.setBounds(140, 20, 180, 20);

        jLabel_Applied.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel5.add(jLabel_Applied);
        jLabel_Applied.setBounds(140, 40, 180, 20);

        jLabel_System.setForeground(new java.awt.Color(153, 0, 153));
        jLabel_System.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel5.add(jLabel_System);
        jLabel_System.setBounds(140, 60, 180, 20);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(30, 310, 330, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
// TODO add your handling code here:
        xpos = this.getLocation().x;
        ypos = this.getLocation().y;
        //this.setExtendedState(java.awt.Frame.ICONIFIED);
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
// TODO add your handling code here:
        this.setSize(391,453+35);     
        this.setLocation(xpos,ypos);
    }//GEN-LAST:event_formWindowActivated

    private void jButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetActionPerformed
// TODO add your handling code here:           
        dm.GDev.setDisplayMode(dm.orgDm);
        jLabel_Applied.setText("["+dm.orgDm.getWidth()+" x "+dm.orgDm.getHeight()+"] ["+dm.orgDm.getBitDepth()+" bpp] ["+dm.orgDm.getRefreshRate()+" Hz]");
        this.setSize(391,453+35);
    }//GEN-LAST:event_jButton_ResetActionPerformed

    private void jButton_TestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TestActionPerformed
// TODO add your handling code here:
        tmode = dm.getMode(jSlider_Resolution.getValue(),jSlider_Depth.getValue(),jSlider_Rate.getValue());
        dm.GDev.setDisplayMode(tmode);
        jLabel_Applied.setText("["+tmode.getWidth()+" x "+tmode.getHeight()+"] ["+tmode.getBitDepth()+" bpp] ["+tmode.getRefreshRate()+" Hz]");
        this.setSize(391,453+35);     
        
    }//GEN-LAST:event_jButton_TestActionPerformed

    private void jSlider_DepthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_DepthStateChanged
// TODO add your handling code here:           
        jLabel_Depth.setText("Depth : "+dm.bits[jSlider_Resolution.getValue()].get(jSlider_Depth.getValue()).toString()+" bpp");
        jLabel_Available.setText("["+dm.res.get(jSlider_Resolution.getValue()).toString()+"] ["+dm.bits[jSlider_Resolution.getValue()].get(jSlider_Depth.getValue()).toString()+" bpp] ["+dm.rrates[jSlider_Resolution.getValue()].get(jSlider_Rate.getValue()).toString()+" Hz]");
    }//GEN-LAST:event_jSlider_DepthStateChanged

    private void jSlider_RateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_RateStateChanged
// TODO add your handling code here:
        jLabel_Rate.setText("Rate : "+dm.rrates[jSlider_Resolution.getValue()].get(jSlider_Rate.getValue()).toString()+" Hz");                
        jLabel_Available.setText("["+dm.res.get(jSlider_Resolution.getValue()).toString()+"] ["+dm.bits[jSlider_Resolution.getValue()].get(jSlider_Depth.getValue()).toString()+" bpp] ["+dm.rrates[jSlider_Resolution.getValue()].get(jSlider_Rate.getValue()).toString()+" Hz]");
    }//GEN-LAST:event_jSlider_RateStateChanged

    private void jSlider_ResolutionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_ResolutionStateChanged
// TODO add your handling code here:
        setSliders(1);
        setSliders(2);
        jLabel_Resolution.setText("Width x Height : "+dm.res.get(jSlider_Resolution.getValue()).toString());
        jLabel_Rate.setText("Rate : "+dm.rrates[jSlider_Resolution.getValue()].get(jSlider_Rate.getValue()).toString()+" Hz");                
        jLabel_Depth.setText("Depth : "+dm.bits[jSlider_Resolution.getValue()].get(jSlider_Depth.getValue()).toString()+" bpp");
        jLabel_Available.setText("["+dm.res.get(jSlider_Resolution.getValue()).toString()+"] ["+dm.bits[jSlider_Resolution.getValue()].get(jSlider_Depth.getValue()).toString()+" bpp] ["+dm.rrates[jSlider_Resolution.getValue()].get(jSlider_Rate.getValue()).toString()+" Hz]");
    }//GEN-LAST:event_jSlider_ResolutionStateChanged

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
// TODO add your handling code here:
        dm.GDev.setDisplayMode(dm.orgDm);
        System.exit(0);
    }//GEN-LAST:event_jButton_ExitActionPerformed
    
    public void setSliders(int no)
    {   
        if(no==0)
        {
            jSlider_Resolution.setMaximum(dm.res.size()-1);
        }
        else if(no==1)
        {        
            jSlider_Depth.setMaximum(dm.bits[jSlider_Resolution.getValue()].size()-1);
        }
        else if(no==2)
        {      
            jSlider_Rate.setMaximum(dm.rrates[jSlider_Resolution.getValue()].size()-1);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try
        { 
            javax.swing.JFrame.setDefaultLookAndFeelDecorated(true);
            javax.swing.JDialog.setDefaultLookAndFeelDecorated(true);
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");             
        } catch (Exception ex) {
            System.out.println("Failed loading L&F: ");
            System.out.println(ex);
        }   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Disp_Prop().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_Reset;
    private javax.swing.JButton jButton_Test;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Applied;
    private javax.swing.JLabel jLabel_Available;
    private javax.swing.JLabel jLabel_Depth;
    private javax.swing.JLabel jLabel_Rate;
    private javax.swing.JLabel jLabel_Resolution;
    private javax.swing.JLabel jLabel_System;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSlider jSlider_Depth;
    private javax.swing.JSlider jSlider_Rate;
    private javax.swing.JSlider jSlider_Resolution;
    // End of variables declaration//GEN-END:variables
    
}
